---
- include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest

- name: upload nginx main config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
