---
- hosts: kimchi
  become: yes
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - kimchi.lxneng.com
    docker_users:
      - admin

  roles:
    - common
    - docker
    - nginx
    - letsencrypt
