- hosts: localhost
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user }}"
          visual_studio_code_extensions:
            - vscodevim.vim
            - ms-python.python
            - ms-python.vscode-pylance
            - ms-toolsai.jupyter
            - golang.go
            - matklad.rust-analyzer
            - scala-lang.scala
            - octref.vetur
            - karunamurti.tera

            - rebornix.ruby
            - wingrunr21.vscode-ruby
            - castwide.solargraph
            - kaiwood.endwise
            - aliariff.vscode-erb-beautify
            - rayhanw.erb-helpers

            - redhat.vscode-yaml
            - marp-team.marp-vscode
            - aaron-bond.better-comments

            - GitHub.copilot
            - github.github-vscode-theme
            - vscode-icons-team.vscode-icons

            - mtxr.sqltools
            - mtxr.sqltools-driver-pg
            - mtxr.sqltools-driver-mysql

            - formulahendry.auto-rename-tag
            - pnp.polacode
            - mushan.vscode-paste-image
            - bradlc.vscode-tailwindcss

          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings:
            {
              "editor.fontSize": 16,
              "editor.rulers": [80, 120],
              "editor.bracketPairColorization.enabled": true,
              "terminal.integrated.fontFamily": "MesloLGS NF",
              "workbench.colorTheme": "GitHub Dark Dimmed",
              "workbench.iconTheme": "vscode-icons",

              "editor.formatOnSave": true,
              "solargraph.autoformat": true,
              "solargraph.diagnostics": true,
              "solargraph.formatting": true,
              "vim.disableExtension": true,
              "pasteImage.path": "${currentFileDir}/images",

              "python.formatting.provider": "black",
              "python.formatting.blackArgs": ["--line-length=80"],
              "python.sortImports.args": ["--profile", "black"],
              "[python]":
                {
                  "editor.codeActionsOnSave":
                    { "source.organizeImports": true },
                },

              "sqltools.format":
                {
                  "reservedWordCase": "upper",
                  "language": "sql",
                  "linesBetweenQueries": 2,
                },
            }
