---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: install apt packages
  apt:
    name: '{{item}}'
  loop: "{{ default_pkgs + extra_pkgs }}"

- name: install overmind
  shell: |
    curl -sSL https://github.com/DarthSim/overmind/releases/download/v2.2.2/overmind-v2.2.2-linux-amd64.gz | gunzip > /usr/local/bin/overmind
    chmod +x /usr/local/bin/overmind
  args:
    creates: /usr/local/bin/overmind

- name: install zoxide
  become: no
  shell: curl -sS https://webinstall.dev/zoxide | bash
  args:
    creates: $HOME/.local/bin/zoxide
